### PR TITLE
django 3.0 compatibility - six

### PR DESCRIPTION
**Pull request by jerzyk**

### CODE REVIEW

**Comment by jrief** [comment]
Rather than importing `six`, I would prefer to drop support for Python-2.7 altogether.
Eventually, Python-2 reaches end of life in January, so developers who still stick on it, must stay with older versions of easy-thumbnails.

**Comment by jaap3** [comment]
This is mostly a duplicate of #527

**Comment by jaap3** [comment]
This can be closed now #533 is merged

**Comment by Mogost** [comment]
@jrief Please close this

**Pull request closed without merging**
