### PR TITLE
fix #600: Сhange deprecated pillow constants

### LINKED ISSUE #600: ANTIALIAS is deprecated and will be removed in Pillow 10
The code in https://github.com/SmileyChris/easy-thumbnails/blob/bc39d7ec3f4c72b000a82f7838eb3c16bcaa86c7/easy_thumbnails/processors.py#L194-L199 triggers a deprecation warning from Pillow:

> DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.

The `LANCZOS` constant has been available since Pillow 2.7.0.

### PR DESCRIPTION
**Pull request by dnazymok**
Fixes #600

Changed the constants, which will be removed in Pillow 10.0.0 based on list:
https://pillow.readthedocs.io/en/stable/releasenotes/9.1.0.html#deprecations

### CODE REVIEW

**Comment by jaap3** [comment]
easy_thumbnails does not set a lower bound for the Pillow requirement. In practice this can mean that any old version of Pillow might be used together with easy-thumbnails. These new constants have been introduced recently, and do not exist on older versions. I think some sort of compatibility shim should be in place.

**Comment by jrief** [comment]
@dnazymok in which version did Pillow introduce the new constants `Image.Resampling.LANCZOS` and `Image.Transpose.…`? 

I then would also like to see a minimum requirement constraint here:
https://github.com/SmileyChris/easy-thumbnails/blob/bc39d7ec3f4c72b000a82f7838eb3c16bcaa86c7/setup.py#L36

**Comment by dnazymok** [comment]
> @dnazymok in which version did Pillow introduce the new constants `Image.Resampling.LANCZOS` and `Image.Transpose.…`?
> 
> I then would also like to see a minimum requirement constraint here:
> 
> https://github.com/SmileyChris/easy-thumbnails/blob/bc39d7ec3f4c72b000a82f7838eb3c16bcaa86c7/setup.py#L36

As I found out, these constants were added in the new version 9.1.0, so I added some compatibility in the last commit

**Comment by dnazymok** [comment]
@jrief can you look at the last commit, it solves the compatibility problem

**Comment by sHooPmyWooP** [comment]
Any update on this? I'd really like to get rid of the Warnings.

**Pull request merged**
