### PR TITLE
Support Django 3.1

### PR DESCRIPTION
**Pull request by jaap3**

### CODE REVIEW

**Comment by jaap3** [comment]
Please look at the individual commits to see why things were added/removed ;)

**Comment by jrief** [comment]
Thanks.

**Comment by jaap3** [comment]
Ah, I missed something. The list of classifiers in `setup.py` doesn't yet contain `'Framework :: Django :: 3.1'`.

Do you want me to make a additional PR?

**Comment by jrief** [comment]
I did it, never mind.

**Pull request merged**
