### PR TITLE
Remove support for Django < 1.11

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by jrief** [comment]
I will merge this pull request later this year. Feel free to ping me whenever you want.

Since that version (3.0) will support Django-2.+, and hence only Python 3, someone should clean up the code and remove all compatibility layers for Python-2.7, such as `django.utils.six`, `unicode_literals`, `__unicode__`, etc.

**Comment by timgraham** [comment]
This could be merged now as Django < 1.11 are unsupported. It's not till Django 3.0 support is added in December 2019 that support for Django 1.11 (and hence Python 2) will be dropped.

**Comment by MrCordeiro** [comment]
Hello, with Django 3 officially out, has any Contributor had the chance to solve these merge conflicts? (@jrief, you said we could ping you 😀 )

**Comment by jrief** [comment]
@timgraham could you please retest with a real project using Django-3.0. I then will release the next release.

**Comment by timgraham** [comment]
I'm no longer maintaining the project where I used this.

**Pull request merged**
