### PR TITLE
Also test against Python 3.9, 3.10, Django 3.2 and Django main

### PR DESCRIPTION
**Pull request by jaap3**

### CODE REVIEW

**Comment by jrief** [comment]
won't merge until all dependencies are fixed.

**Comment by jaap3** [comment]
Not sure what you mean by dependencies, the only dependencies are Django and Pillow right? Currently easy_thumbnails can be installed with Django 3.2, it just isn't tested against it.

If you mean the test failure, I just forced push a type fix. I think that should do the trick :)

**Comment by jaap3** [comment]
@jrief any chance you can take a look at this again?

**Comment by jaap3** [comment]
I've rebased this on master so the tests run on GH Actions. I've also added Python 3.10 and Django's main branch to the test matrix (tests are allowed to fail on the main branch, it's just nice to have an early indication when that happens)

**Comment by jaap3** [comment]
@jrief A patch release after merging this PR would be much appreciated. easy-thumbnails is currently blocking the upgraded to the next Django LTS on a couple of our projects.

**Pull request merged**
